apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: prod
  annotations:
    argocd.argoproj.io/sync-wave: "5"  
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
