apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: prod
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "$DB_NAME"
            - name: MYSQL_USER
              value: "$DB_USER"
            - name: MYSQL_PASSWORD
              value: "$DB_PASS"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-pv-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
        - name: mysql-pv-storage
          persistentVolumeClaim:
            claimName: ebs-pvc

            # I'm variabling the db creds and adding this in jenkins cred so uisng envsubst i'm replacing the creds"
            # sh "envsubst '\$DB_USER \$DB_PASS \$DB_NAME' < mysql-deployment.yml > mysql-deployment.yml"

