apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  annotations:
    argocd.argoproj.io/sync-wave: "2"
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
  #parameters:
  #type: gp2

