apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app
  namespace: prod
  annotations:
    argocd.argoproj.io/sync-wave: "6"  
  labels:
    app: two-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
        - name: two-tier-app
          image: ${NEW_IMAGE}
          env:
            - name: MYSQL_HOST
              value: mysql          
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "mydb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
